### ISSUE TITLE
Can't create plane constraint between two objects

### ISSUE THREAD

**Issue by faber80** [hamish2014/FreeCAD_assembly2#23] opened 2015-06-03 08:56 UTC
I modelled two beams and I tried to constrain two faces with no success with a plane constraint. Is it a bug ?
![beam_joint](https://cloud.githubusercontent.com/assets/12728287/7956282/2cdc791c-09df-11e5-93d0-5d8725027a9d.jpg)

**Comment by hamish2014** [comment] 2015-06-03 16:10
Is this what you where trying to achieve?
![plane_constraint](https://cloud.githubusercontent.com/assets/7496850/7965091/9896e318-0a1b-11e5-82ec-82ad4e5efc70.png)

From the screen shot, it seems that you are using FreeCAD on Windows.
Are you by any chance using the 64 bit version/build?
If so, then this could be a duplicate of an earlier issue...

**Comment by faber80** [comment] 2015-06-04 09:24
Yes I'm under windows. I'll try under ubuntu x64 then I'll report if it works

**Comment by faber80** [comment] 2015-06-04 09:34
Sorry at the moment I can't try. I'have an UbuntuX64 distro on a virtual machine under windows (VMware) and I have a series of problem with Graphic card and opengl.

**Comment by faber80** [comment] 2015-06-04 16:02
![freecad-error](https://cloud.githubusercontent.com/assets/12728287/7988443/c5846846-0ae3-11e5-94ae-cd73b247a11c.jpg)

Same error on Ubuntu 15.04 x64 virtual machine

**Comment by hamish2014** [comment] 2015-06-05 06:33
Ok, please run the following tests and post your results.


#### Test numpy

from the terminal on your Ubuntu machine run (the $ suffix)

```
  $ sudo apt-get install python-nose
  $ python
  >>> import numpy
  >>> numpy.test()
```
Does the test give the OK result?

#### Test the assembly 2 workbench
```
  $ cd ~/.FreeCAD/Mod/FreeCAD_assembly2
  $ python assembly2solver.py
```
Do all the test case succeed?
Does the test script output something like 

*All 16 tests passed, time taken 13.49s*

?

**Comment by faber80** [comment] 2015-06-05 08:36
![test1](https://cloud.githubusercontent.com/assets/12728287/8002397/b0052f92-0b6e-11e5-9331-b980674f3079.jpg)
![test2](https://cloud.githubusercontent.com/assets/12728287/8002399/b15f3162-0b6e-11e5-94ca-435ca280a6a0.jpg)

All test passed

**Comment by hamish2014** [comment] 2015-06-05 08:43
Good, so that all works.
- Please provide a step by step break down of how you setup the plane constraint causing the crash.
- Can you define other plane constraints successfully, or do all variants fail.
- could you copy and paste the FreeCAD report view output, detailing the error.
Thanks

**Comment by faber80** [comment] 2015-06-05 09:40
1- I press add plane constrint button
2- I pick a plane face on Beam 1
3- I pick a plane face on Beam 2

This is the report error:
UNABLE TO SOLVE CONSTRAINTS! info:<AxisAlignmentUnion System profilato_100x100_import02:Face7-profilato_100x100_import01:Face18 heirachy 1> no degrees-of-freedom to adjust to satify constraints:
<AxisAlignmentUnion System profilato_100x100_import02:Face7-profilato_100x100_import01:Face18 heirachy 1>
    <FixedObjectSystem profilato_100x100_import01> 0 degrees of freedom
    <FixedObjectSystem profilato_100x100_import02> 0 degrees of freedomremoved constraint planeConstraint01

All costraints don't work.
It seems the two beam have all the six degrees of freedom fixed

**Comment by hamish2014** [comment] 2015-06-05 10:53
Perhaps both Beam 1 and Beam 2 have a fixed position?
Check under the import object properties

**Comment by faber80** [comment] 2015-06-05 11:42
![properties](https://cloud.githubusercontent.com/assets/12728287/8005280/804a31b6-0b88-11e5-8b3d-191285f6623f.jpg)

These are all properties I see. Where can I check if the part have a fixed position?

**Comment by hamish2014** [comment] 2015-06-05 11:44
Hi Faber, check under the data (dati) tab, not the view tab.

**Comment by faber80** [comment] 2015-06-05 11:51
![data](https://cloud.githubusercontent.com/assets/12728287/8005379/b58bd6a8-0b89-11e5-9883-09f99b0904c2.jpg)

Sorry I'm a newbie with free cad. 
Fram Data Tab seems the objects have a placement

**Comment by hamish2014** [comment] 2015-06-05 11:55
No worries :)
Look under the **import part** category, and you will see the **fixed Position** attribute.
Make sure only *one of the beams* has `fixed Position = true'

**Comment by faber80** [comment] 2015-06-05 11:59
Ok I checked fixed position to false and now it works! Thank you very much for your support and sorry if I waste your time. I'll extensively test assembly workbench. I worked a lot with CATIA, SOLIDWORKS and PRO-E and I think these module is very important to make FreeCad competitive with professional CAD. Thank you for your work.

**Comment by hamish2014** [comment] 2015-06-05 12:05
Pleasure.
I recommend you update to the latest version of the Assembly 2 workbench.
Specifically, my guess is that you got 2 parts with fixed position, by copying a part with a fixed_Position=True.
In the newer versions of Assembly2, the default behaviour is that copied parts have fixed_Position=False irrespective of the parent part.

**Closed by hamish2014** 2015-06-05 12:05 UTC

**Comment by faber80** [comment] 2015-06-05 12:13
I download the version I used from ppa:freecad-community/ppa isn't the right way to get the most updated version?

**Comment by hamish2014** [comment] 2015-06-05 12:19
Hi, yes that is the correct way.
According to my understanding some FreeCAD community members have setup this ppa so that it is linked to the lastest version on GitHub.
I wonder if something is wrong with the ppa update system.
